//*****************************************************************************
// pin_mux_config.c
// Generated by TI PinMux 4.0.1543 — modified for IR receiver on PIN_50
//*****************************************************************************
#include "pin_mux_config.h"
#include "hw_types.h"
#include "hw_memmap.h"
#include "hw_gpio.h"
#include "pin.h"
#include "gpio.h"
#include "prcm.h"

void PinMuxConfig(void)
{
    //
    // Enable Peripheral Clocks
    //
    PRCMPeripheralClkEnable(PRCM_I2CA0,  PRCM_RUN_MODE_CLK);
    PRCMPeripheralClkEnable(PRCM_GPIOA0, PRCM_RUN_MODE_CLK);
    PRCMPeripheralClkEnable(PRCM_GPIOA3, PRCM_RUN_MODE_CLK);
    PRCMPeripheralClkEnable(PRCM_GSPI,   PRCM_RUN_MODE_CLK);
    PRCMPeripheralClkEnable(PRCM_UARTA0, PRCM_RUN_MODE_CLK);
    PRCMPeripheralClkEnable(PRCM_TIMERA0,PRCM_RUN_MODE_CLK); // needed for IR timestamping

    //
    // I2C — BMA222 accelerometer (Lab 3 carry-over)
    //
    PinTypeI2C(PIN_01, PIN_MODE_1);  // SCL
    PinTypeI2C(PIN_02, PIN_MODE_1);  // SDA

    //
    // SPI — OLED display (Lab 2 carry-over)
    //
    PinTypeSPI(PIN_05, PIN_MODE_7);  // GSPI_CLK
    PinTypeSPI(PIN_07, PIN_MODE_7);  // GSPI_MOSI

    //
    // UART — terminal (Lab 1 carry-over)
    //
    PinTypeUART(PIN_55, PIN_MODE_3); // UART0_TX
    PinTypeUART(PIN_57, PIN_MODE_3); // UART0_RX

    //
    // IR Receiver DATA --> GPIO INPUT (PIN_50 = GPIO_00, bit 0x1 on GPIOA0)
    // FIX: was GPIO_DIR_MODE_OUT — must be IN for the receiver to drive the pin
    //
    PinTypeGPIO(PIN_50, PIN_MODE_0, false);
    GPIODirModeSet(GPIOA0_BASE, 0x1, GPIO_DIR_MODE_IN);  // <-- INPUT, no write needed

    //
    // OLED RST --> GPIO (PIN_18 = bit 0x10 on GPIOA3), idle HIGH
    //
    PinTypeGPIO(PIN_18, PIN_MODE_0, false);
    GPIODirModeSet(GPIOA3_BASE, 0x10, GPIO_DIR_MODE_OUT);
    GPIOPinWrite(GPIOA3_BASE, 0x10, 0x10);

    //
    // OLED CS --> GPIO (PIN_61 = bit 0x40 on GPIOA0), idle HIGH
    //
    PinTypeGPIO(PIN_61, PIN_MODE_0, false);
    GPIODirModeSet(GPIOA0_BASE, 0x40, GPIO_DIR_MODE_OUT);
    GPIOPinWrite(GPIOA0_BASE, 0x40, 0x40);

    //
    // OLED DC --> GPIO (PIN_62 = bit 0x80 on GPIOA0), idle HIGH
    //
    PinTypeGPIO(PIN_62, PIN_MODE_0, false);
    GPIODirModeSet(GPIOA0_BASE, 0x80, GPIO_DIR_MODE_OUT);
    GPIOPinWrite(GPIOA0_BASE, 0x80, 0x80);
}

